### ISSUE TITLE
How do i specify a currency? "NGN" or "USD"

### ISSUE THREAD

**Issue by Joezzy** [DEVSOG12/flutter_paystack_payment#1]

**Comment by mathiasgodwin** [comment]
@Joezzy based on the documentation [here](https://paystack.com/docs/api/#transaction-initialize), that's how to do it. 

> The transaction currency (NGN, GHS, ZAR or USD). Defaults to your integration currency.

**Comment by DEVSOG12** [comment]
@Joezzy  Under the charge method, you have to indicate the parameter currency. To do this like this:

`
    Charge charge = Charge()
      ..amount = 10000 // In base currency
      ..email = 'customer@email.com'
      ..card = _getCardFromUI();
      ..currency = "USD"
`

**Comment by DEVSOG12** [comment]
Closing.
